name: demo_yummy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  http: ^1.2.0
  permission_handler: ^11.3.1 
  webview_flutter: ^3.0.4
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  curved_navigation_bar: ^1.0.6
  circular_profile_avatar: ^2.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  shared_preferences: ^2.2.0
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.2.2
  google_sign_in: ^6.2.1
  speech_to_text: ^6.6.0 

  intl: ^0.18.1 

  get: 4.6.6
  
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.1


  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/google.png


